version: '3'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - .:/app
    environment:
      - CACHE_DIR=/app/data
      - DB_PATH=/app/data/db.sqlite
      - LOG_DIR=/app/logs
      - LOG_LEVEL=INFO
      - API_RATE_LIMIT=2.0
    restart: unless-stopped