version: '3.8'

services:
  mlb-pitcher-analyzer:
    build: .
    container_name: mlb-pitcher-analyzer
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.yml:/app/config.yml
    environment:
      - MLB_APP_DEBUG=false
      - MLB_LOG_LEVEL=INFO
      - MLB_CACHE_DIR=/app/data
      - MLB_DB_PATH=/app/data/db.sqlite
      - MLB_LOG_DIR=/app/logs
      - MLB_API_RATE_LIMIT=2.0
      - MLB_API_MAX_RETRIES=3
    restart: unless-stopped