version: '3.8'

services:
  mlb-pitcher-analyzer:
    build: .
    container_name: mlb-pitcher-analyzer
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - CACHE_DIR=/app/data
      - DB_PATH=/app/data/db.sqlite
      - LOG_DIR=/app/logs
      - LOG_LEVEL=INFO
      - API_RATE_LIMIT=2.0
    restart: unless-stopped